### ISSUE TITLE
Using == instead of = in a conditional statement leaves MiniBASIC

### ISSUE THREAD

**Issue by chinhouse** [JoeStrout/minibasic#10]
![Screenshot 2023-09-18 114650](https://github.com/JoeStrout/minibasic/assets/15525424/de82568d-02da-47f8-8abc-81504c9f93ad)

**Comment by JoeStrout** [comment]
Good catch!  We'll get that fixed soon.

**Comment by JoeStrout** [comment]
Now fixed.
