### ISSUE TITLE
Comments in Basic programs

### ISSUE THREAD

**Issue by eddavis2** [JoeStrout/minibasic#3]
1) While REM is supported, rem is not.  Would be nice to support both.
2) The single quote is used as a replacement for rem in some dialects - such as GW-Basic. Would be nice to have that.

**Comment by JoeStrout** [comment]
Good catch on case-sensitivity of REM!  That was not intended.  I'll get that fixed right away.

I'm going to hold off on the single quote though, at least for now.  That's not standard enough to really fit with MiniBASIC's objectives.

Thank you for the report!

**Comment by JoeStrout** [comment]
Now fixed for v0.9.3.
