### ISSUE TITLE
Can't negate a variable in v0.9.4

### ISSUE THREAD

**Issue by eddavis2** [JoeStrout/minibasic#6]
In 0.9.3
![image](https://user-images.githubusercontent.com/75323909/222931148-09ab4253-0718-4ffb-8fc2-3167c44cbbe1.png)

In 0.0.4
![image](https://user-images.githubusercontent.com/75323909/222931097-829193b9-8d88-46ee-9004-cac0046cbc6e.png)

**Comment by JoeStrout** [comment]
Great catch!  I'm lucky to have you on the team!
