### ISSUE TITLE
Microsoft BASIC-80: line input

### ISSUE THREAD

**Issue by eddavis2** [JoeStrout/minibasic#7]
Sure would be nice if **MiniBasic** has Microsoft BASIC-80's **line input** command.  As it is, there is no reliable way to get a line of arbitrary input from the user.

**Comment by JoeStrout** [comment]
Why not?  `INPUT A$` gets a line of arbitrary input from the user, doesn't it?

**Comment by sammymitchell** [comment]
Upon further investigation, it appears to be a problem with arrays:

![image](https://user-images.githubusercontent.com/75181897/224161237-9aedd2f4-907f-43a9-a8d7-8a7b1ba00ed2.png)

a$ takes input ok, but pgm$(0) gets truncated.

**Comment by eddavis2** [comment]
Upon further investigation, the problem is with input and arrays:
input to a$ works fine, but pgm$(0) gets truncated.
![image](https://user-images.githubusercontent.com/75323909/224161767-9311b8bd-30ae-493d-b3a7-5b66c64759b8.png)

**Comment by JoeStrout** [comment]
OK, that makes some sense.  Good job narrowing it down!  I'll get it fixed (though it might have to wait till next week — I'm traveling without my computer this weekend).

**Comment by JoeStrout** [comment]
Fixed in v0.9.5.
